POST http://127.0.0.1:8080/run 
Content-Type: application/json

{
    "client_name": "monkeymum_com",
    "keboola_trigger": {
        "keboola_orchestration_trigger_run_id": "84244497",
        "keboola_storage_api_token": "TOKEN",
        "keboola_job_max_runtime_seconds": 120
    },
    "dataform_trigger": {
        "dataform_repo_name": "monkeymum_com",
        "git_commitish": "development"
    },
    "slack_notification": {
        "slack_oauth_token": "TOKEN"
    }
}