steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "gen2_http_client_reporting_dataform_trigger",
        "--entry-point=hello_http",
        "--region=europer-west1",
        "--trigger-http",
        "--runtime=python312",
        "--source=gen2-http-client-reporting-dataform-trigger",
      ]
