steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
    - "functions"
    - "deploy"
    - "cloud_build_gen2_http_client_reporting_dataform_trigger"
    - "--entry-point=run"
    - "--region=europe-west3"
    - "--trigger-http"
    - "--runtime=python312"
    - "--source=gen2-http-client-reporting-dataform-trigger"
options:
  logging: CLOUD_LOGGING_ONLY
# steps:
#   options:
#     default_logs_bucket_behavior: "CLOUD_LOGGING_ONLY"
#   - name: "gcr.io/cloud-builders/gcloud"
#     args:
#       [
#         "functions",
#         "deploy",
#         "gen2_http_client_reporting_dataform_trigger",
#         "--entry-point=hello_http",
#         "--region=europer-west1",
#         "--trigger-http",
#         "--runtime=python312",
#         "--source=gen2-http-client-reporting-dataform-trigger",
#       ]
