steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "gen2_http_client_reporting_slack_alerting",
        "--gen2",
        "--allow-unauthenticated",
        "--entry-point=run",
        "--region=europe-west1",
        "--trigger-http",
        "--runtime=python312",
        "--timeout=60",
        "--memory=2Gi",
        "--cpu=1",
        "--concurrency=5",
        "--min-instances=0",
        "--max-instances=5",
        "--source=.",
      ]
    dir: "niftyminds-client-reporting/gen2_http_client_reporting_slack_alerting"
options:
  logging: CLOUD_LOGGING_ONLY
