steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "cloud_build_gen2_http_client_reporting_keboola_orchestrationV2_trigger",
        "--gen2",
        "--allow-unauthenticated",
        "--entry-point=run",
        "--region=europe-west1",
        "--trigger-http",
        "--runtime=python312",
        "--source=.",
      ]
    dir: "niftyminds-client-reporting/gen2_http_client_reporting_keboola_orchestrationV2_trigger"
options:
  logging: CLOUD_LOGGING_ONLY