steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "gen2_http_upgates_api_connector",
        "--gen2",
        "--allow-unauthenticated",
        "--entry-point=run",
        "--region=europe-west1",
        "--trigger-http",
        "--runtime=python312",
        "--timeout=600",
        "--memory=2Gi",
        "--cpu=1",
        "--concurrency=5",
        "--min-instances=0",
        "--max-instances=5",
        "--source=.",
      ]
    dir: "monkeymum/gen2_http_upgates_api_connector"
options:
  logging: CLOUD_LOGGING_ONLY
# steps:
#   options:
#     default_logs_bucket_behavior: "CLOUD_LOGGING_ONLY"
#   - name: "gcr.io/cloud-builders/gcloud"
#     args:
#       [
#         "functions",
#         "deploy",
#         "gen2_http_upgates_api_connector",
#         "--entry-point=hello_http",
#         "--region=europer-west1",
#         "--trigger-http",
#         "--runtime=python312",
#         "--source=gen2-http-client-reporting-dataform-trigger",
#       ]
